title: "Learn2CTF"
#tagline: "MSU Learn2CTF club"
description: ""
github_username: hacr-lab
baseurl: "/learn2ctf"
url: ""

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: itstorque/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - About.md
  - Join.md
  - Events.md

# set the size of the text to 'large' or 'small', default is small
font-size: large
